version: '3'
services:
  tg-claude-bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_MODEL=${CLAUDE_MODEL}
    restart: always
